SIC_MAPPING = {
    "0100": "Agricultural Production-Crops",
    "0200": "Agricultural Prod-Livestock & Animal Specialties",
    "0700": "Agricultural Services",
    "0800": "Forestry",
    "0900": "Fishing, Hunting and Trapping",
    "1000": "Metal Mining",
    "1040": "Gold and Silver Ores",
    "1090": "Miscellaneous Metal Ores",
    "1220": "Bituminous Coal & Lignite Mining",
    "1221": "Bituminous Coal & Lignite Surface Mining",
    "1311": "Crude Petroleum & Natural Gas",
    "1381": "Drilling Oil & Gas Wells",
    "1382": "Oil & Gas Field Exploration Services",
    "1389": "Oil & Gas Field Services, NEC",
    "1400": "Mining & Quarrying of Nonmetallic Minerals (No Fuels)",
    "1520": "General Bldg Contractors - Residential Bldgs",
    "1531": "Operative Builders",
    "1540": "General Bldg Contractors - Nonresidential Bldgs",
    "1600": "Heavy Construction Other Than Bldg Const - Contractors",
    "1623": "Water, Sewer, Pipeline, Comm & Power Line Construction",
    "1629": "Heavy Construction, Not Elsewhere Classified",
    "1700": "Construction - Special Trade Contractors",
    "1731": "Electrical Work",
    "2000": "Food and Kindred Products",
    "2011": "Meat packing plants",
    "2013": "Sausages & Other Prepared Meat Products",
    "2015": "Poultry Slaughtering and Processing",
    "2020": "Dairy Products",
    "2024": "Ice cream & frozen desserts",
    "2030": "Canned, Frozen & Preserved Fruit, Veg & Food Specialties",
    "2033": "Canned, Fruits, Veg, Preserves, Jams & Jellies",
    "2040": "Grain Mill Products",
    "2050": "Bakery Products",
    "2052": "Cookies & Crackers",
    "2060": "Sugar & Confectionery Products",
    "2070": "Fats & Oils",
    "2080": "Beverages",
    "2082": "Malt Beverages",
    "2086": "Bottled & Canned Soft Drinks & Carbonated Waters",
    "2090": "Miscellaneous Food Preparations & Kindred Products",
    "2092": "Prepared Fresh or Frozen Fish & Seafood",
    "2100": "Tobacco Products",
    "2111": "Cigarettes",
    "2200": "Textile Mill Products",
    "2211": "Broadwoven Fabric Mills, Cotton",
    "2221": "Broadwoven Fabric Mills, Man Made Fiber & Silk",
    "2250": "Knitting Mills",
    "2253": "Knit Outerwear Mills",
    "2273": "Carpets & Rugs",
    "2300": "Apparel & Other Finished Prods of Fabrics & Similar Matl",
    "2320": "Men's & Boys' Furnishings, Work Clothing, & Allied Garments",
    "2330": "Women's, Misses', and Juniors Outerwear",
    "2340": "Women's, Misses', Children's & Infant's Undergarments",
    "2390": "Miscellaneous Fabricated Textile Products",
    "2400": "Lumber & Wood Products (No Furniture)",
    "2421": "Sawmills & Planing Mills, General",
    "2430": "Millwood, Veneer, Plywood, & Structural Wood Members",
    "2451": "Mobile homes",
    "2452": "Prefabricated Wood Bldgs & Components",
    "2510": "Household Furniture",
    "2511": "Wood Household Furniture, (No Upholstered)",
    "2520": "Office Furniture",
    "2522": "Office Furniture (No Wood)",
    "2531": "Public Bldg & Related Furniture",
    "2540": "Partitions, Shelvg, Lockers, & office & Store Fixtures",
    "2590": "Miscellaneous Furniture & Fixtures",
    "2600": "Papers & Allied Products",
    "2611": "Pulp Mills",
    "2621": "Paper Mills",
    "2631": "Paperboard Mills",
    "2650": "Paperboard Containers & Boxes",
    "2670": "Converted Paper & Paperboard Prods (No Containers/Boxes)",
    "2673": "Plastics, Foil & Coated Paper Bags",
    "2711": "Newspapers: Publishing or Publishing & Printing",
    "2721": "Periodicals: Publishing or Publishing & Printing",
    "2731": "Books: Publishing or Publishing & Printing",
    "2732": "Book Printing",
    "2741": "Miscellaneous Publishing",
    "2750": "Commercial Printing",
    "2761": "Manifold Business Forms",
    "2771": "Greeting Cards",
    "2780": "Blankbooks, Looseleaf Binders & Bookbinding & Related Work",
    "2790": "Service Industries For The Printing Trade",
    "2800": "Chemicals & Allied Products",
    "2810": "Industrial Inorganic Chemicals",
    "2820": "Plastic Material, Synth Resin/Rubber, Cellulos (No Glass)",
    "2821": "Plastic Materials, Synth Resins & Nonvulcan Elastomers",
    "2833": "Medicinal Chemicals & Botanical Products",
    "2834": "Pharmaceutical Preparations",
    "2835": "In Vitro & In Vivo Diagnostic Substances",
    "2836": "Biological Products, (No Diagnostic Substances)",
    "2840": "Soap, Detergents, Cleaning Preparations, Perfumes, Cosmetics",
    "2842": "Specialty Cleaning, Polishing and Sanitation Preparations",
    "2844": "Perfumes, Cosmetics & Other Toilet Preparations",
    "2851": "Paints, Varnishes, Lacquers, Enamels & Allied Prods",
    "2860": "Industrial Organic Chemicals",
    "2870": "Agricultural chemicals",
    "2890": "Miscellaneous Chemical Products",
    "2891": "Adhesives & Sealants",
    "2911": "Petroleum Refining",
    "2950": "Asphalt Paving & Roofing Materials",
    "2990": "Miscellaneous Products of Petroleum & Coal",
    "3011": "Tires & Inner Tubes",
    "3021": "Rubber & Plastics Footwear",
    "3050": "Gaskets, Packg & Sealg Devices & Rubber & Plastics Hose",
    "3060": "Fabricated Rubber Products, NEC",
    "3080": "Miscellaneous Plastics Products",
    "3081": "Unsupported Plastics Film & Sheet",
    "3086": "Plastics Foam Products",
    "3089": "Plastics Products, NEC",
    "3100": "Leather & Leather Products",
    "3140": "Footwear, (No Rubber)",
    "3211": "Flat Glass",
    "3220": "Glass & Glassware, Pressed or Blown",
    "3221": "Glass Containers",
    "3231": "Glass Products, Made of Purchased Glass",
    "3241": "Cement, Hydraulic",
    "3250": "Structural Clay Products",
    "3260": "Pottery & Related Products",
    "3270": "Concrete, Gypsum & Plaster Products",
    "3272": "Concrete Products, Except Block & Brick",
    "3281": "Cut Stone & Stone Products",
    "3290": "Abrasive, Asbestos & Misc Nonmetallic Mineral Prods",
    "3310": "Steel Works, Blast Furnaces & Rolling & Finishing Mills",
    "3312": "Steel Works, Blast Furnaces & Rolling Mills (Coke Ovens)",
    "3317": "Steel Pipe & Tubes",
    "3320": "Iron & Steel Foundries",
    "3330": "Primary Smelting & Refining of Nonferrous Metals",
    "3334": "Primary Production of Aluminum",
    "3341": "Secondary Smelting & Refining of Nonferrous Metals",
    "3350": "Rolling Drawing & Extruding of Nonferrous Metals",
    "3357": "Drawing & Insulating of Nonferrous Wire",
    "3360": "Nonferrous Foundries (Castings)",
    "3390": "Miscellaneous Primary Metal Products",
    "3411": "Metal Cans",
    "3412": "Metal Shipping Barrels, Drums, Kegs & Pails",
    "3420": "Cutlery, Handtools & General Hardware",
    "3430": "Heating Equip, Except Elec & Warm Air; & Plumbing Fixtures",
    "3433": "Heating Equipment, Except Electric & Warm Air Furnaces",
    "3440": "Fabricated Structural Metal Products",
    "3442": "Metal Doors, Sash, Frames, Moldings & Trim",
    "3443": "Fabricated Plate Work (Boiler Shops)",
    "3444": "Sheet Metal Work",
    "3448": "Prefabricated Metal Buildings & Components",
    "3451": "Screw Machine Products",
    "3452": "Bolts, Nuts, Screws, Rivets & Washers",
    "3460": "Metal Forgings & Stampings",
    "3470": "Coating, Engraving & Allied Services",
    "3480": "Ordnance & Accessories, (No Vehicles/Guided Missiles)",
    "3490": "Miscellaneous Fabricated Metal Products",
    "3510": "Engines & Turbines",
    "3523": "Farm Machinery & Equipment",
    "3524": "Lawn & Garden Tractors & Home Lawn & Gardens Equip",
    "3530": "Construction, Mining & Materials Handling Machinery & Equip",
    "3760": "Guided Missiles & Space Vehicles & Parts",
    "3790": "Miscellaneous Transportation Equipment",
    "3812": "Search, Detection, Navigation, Guidance, Aeronautical Sys",
    "3873": "Watches, Clocks, Clockwork Operated Devices/Parts",
    "3910": "Jewelry, Silverware & Plated Ware",
    "3911": "Jewelry, Precious Metal",
    "7000": "Hotels, Rooming Houses, Camps & Other Lodging Places",
    "7011": "Hotels & Motels",
    "7200": "Services-Personal Services",
    "7310": "Services-Advertising",
    "7311": "Services-Advertising Agencies",
    "7320": "Services-Consumer Credit Reporting, Collection Agencies",
    "7990": "Services-Miscellaneous Amusement & Recreation",
    "7994": "Services-Video Game Arcades",
    "7995": "Services-Gambling Transactions",
    "9995": "Non-Operating Establishments",
}
